{{- if .Values.routes.auth.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: auth
  namespace: envoy-gateway
  {{- $labels := .Values.routes.auth.labels | default dict -}}
  {{- if .Values.routes.auth.oidc.enabled }}
    {{- $_ := set $labels (.Values.routes.auth.oidc.labelKey | default "auth.joeriberman.nl/oidc") (.Values.routes.auth.oidc.labelValue | default "true") -}}
  {{- end }}
  {{- if $labels }}
  labels:
  {{- range $k, $v := $labels }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
      sectionName: web-https
  hostnames:
    - {{ .Values.routes.auth.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: auth-blackhole
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-blackhole
  namespace: envoy-gateway
spec:
  type: ExternalName
  externalName: blackhole.invalid
  ports:
    - port: 80
{{- end }}
