apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: main-gateway-proxy
  namespace: envoy-gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        externalTrafficPolicy: Cluster
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "10.0.0.242"
