apiVersion: v1
kind: Service
metadata:
  name: external-server
  namespace: default
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-server
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.81
    ports:
      - name: https
        port: 443
        protocol: TCP