apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway-public
  annotations:
    'cert-manager.io/revision-history-limit': '1'
    'cert-manager.io/cluster-issuer': letsencrypt-dns
spec:
  gatewayClassName: envoy-gateway
  addresses:
    - type: IPAddress
      value: 10.0.1.2
  listeners:
    - name: web-https
      protocol: HTTPS
      port: 443
      hostname: '*.k8s.joeriberman.nl'  # wildcard listener
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
        - group: ''
          kind: Secret
          name: wildcard-tls  # wildcard TLS certificate