apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: argocd
  annotations:
    'cert-manager.io/revision-history-limit': "1"
    'cert-manager.io/cluster-issuer': letsencrypt-dns
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: main-gateway-proxy
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.joeriberman.nl"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: main-gateway-cert
