---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-client-id
  namespace: default
spec:
  encryptedData:
    client-id: AgCfvLv01BSeMR0kKAROLvkajGcWqkEkcu8XKMhUGkdtBroImAIjOIJftX9rli0kFTu3h3c8UJUTfNY9aBMeHp0HKnb+xYI445C60FM4Zz54kVgS5JI3PEuqdQhwyGntfemmQltL6yM/TgTa2i4bzDA5f1iCCBK3gtdDN/odZo4gM+gZJxvDw2z4L77/LPLO0+xzItXiPHsKmiutxWkNb3dk39a5r5Py39XhJDH5jFF7x+F+k6ebwTAaQRE3NeIxVomjs49EkvINDr720gl2E0YoZQClTV+BOYsj4yu8F/SOG735P5xNZ2jMRYWuJU7Wa05rQmJCHszqpuoUw0UfDvNdW/XLMRkMyBqSfS00snszyjdc5h4DdW0AZS86dcadKIA9I43EsJSPybPSu8YeAUx+fgglcepc0KWZ2MQli1e2j08A3EcuhHqKyTcdk3IRN5PsX3uZ+O89F92y7jY9l+BiWvFijavaQ6CQdbthJjAoMvU+zqUexKHUW1Rh+8rBk6dM5WFOSGTohnIi/PgJzlfEQVEOzcoxuJ8D/DuZ0706+U2ULQkeRgyS6yYs12wMZvlIQUI/tQTHcDagqgtSU282n4FN6vBU6CSfjsuiQb0M0BXgE4NXqdgHgH9Xvf7mbP16JCUXZv45vc1xTx15n06FNXHoXEBbDZG7R3TY3JtA5Mf/UuUf2wVfsNuf9CahN4xBdD+4Nw6PhrJkCUFMho/9CG16ZfjEio4bp46ekF4fv02LoKZDtdFDz29VMdNY1kpHrsIykrxrlDnnv3GfZAEW2zStS5zWzQY=
  template:
    metadata:
      name: oidc-client-id
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-client-secret
  namespace: default
spec:
  encryptedData:
    client-secret: AgAb6gXac1Pf5ZzLpdnr3ezbow/juUpOk1abhDmp5gjir5H+TFpJbbYveqC21djqStwLrovD2tS3DOAniinaWKSOGAq0kQKy6T5si54v9wqQANXUxGR5+js5O8eSD0xKYDHcNLCzGCy2zdeoA9+kTsgdSgIa8/N72nFBGh4JQNkY32id8ETQ6KGFhxG9QxOKchLfyVHH2O8eM9aaiT5hnH/dNdurPlBHo/GFzv69u9gmQv8YBb7mFoRHN7hWtj7E6ZtBSzm5kA6+LcyFBtL/t4eBxslV/CroXruJKwnVeZu4sq7sqQe4Eoi54u6osHfOO51o2uDmlJVe06fhumhdrhsKs6N1TeQk6bT1c8CZ+TVUlTC0/1INPjJlMnTtUZdrItSmZfRORYfjiSShOkEBnwufPS6AUeK8upED7kUkG9g1q507BUF/nAbB0OLMu8VAeQrOY6DRAFsz7Gf68xJzSFSgxyoB13/dtOW/9UVQciycJAnkcX4S1fFsf7F1jldzrMYV3gBRtNrHdz2t1bmX1R3HE8PzaQVQyRSfecPUl1vKD8/dhNWvcPH3oxe/NYehRLNDiLSGgb79Hx+nJIqYKTmmNiTSyQ3QASc2S6Meq1KbHurbDqcNPQdBCGemTRxMJZKiJLqxiW8cZXvalbPRwuMgCckeIw9tSLCrX3I6jN62zRNwgGiDDX5BGV/3t9tHrwSQmX7O68RWH1tcLFVOlfPI+SUTb/d8yKKiSFARgURZ1A5+Lg==
  template:
    metadata:
      name: oidc-client-secret
      namespace: default
    type: Opaque
