---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-client-id
  namespace: envoy-gateway
spec:
  encryptedData:
    client-id: AgAns5PBiK5zV3DeE2t5Z4EMQGB+1U65Gc3K024Lkm1Ybzd6kC2rBM+v0pazPUhWpDNC/961eR/uP2i25m0IwKvf8Nl5xtWoPce2bAditFmLxV1aLQS7TegQfEc3Ue+VwDYB37IkaeKpl5lvVpjLNcMsAlUfOHPuqun3Tvp66snx/xGJkP7YFQ2uBdUUPCC/qVQchuj7yZEmYwvajrZ6IQw3ZcUYFtBLfjNDeZvg5iAOtyax+ZXH5jq4wwkuskfFbelEgdTsq9FNHq/epphUSmXYHzehRm+W3m8D3jeUXbXa/ZdzxvIvHg03gs6VeqZCFXUFpFEmfMNal913uinZnhH65aExXEsF/KL0gvZWxnNfeodxUDkwH4blyrZtCc6Qprx0F2iNyYWOv2iTquiZMfYrhUaiYXNM7hcwM7WozL6GAC2A6guDuLcdf5uIRaUdbqUdtJzjFmOC8A6bl7I2Y5n4JJIdtoNj6jUMyXyPEONKnwsGy4W6E2RhOIeh97hXgia3wbP0a4XGRyiXWBr4kImNUXJ2pl333nZN55/ilmwq+aiMGkHIHUj0zkjQIfJ+9OncDhl/gSe6ZyKKeW6Y6ARnzEJGCEX4jy8j9leBKlkYcrUWY7uoW55CZIM0dpFe8b5IHaCQzaPkTjEM/CowFRYqGS2FL0v6BDHfCB+vCK03xo+Qykg5Wp+K1lzPQ2so/N3Hj+wIisSIGDHW7H5kigRdkPFDc/CKC2LnJEsStH6TFd/8EWsocgvhPcXi3FEPCRVvALPk5qF3kO38/I5m6p2+peq4Lz8MvJY=
  template:
    metadata:
      name: oidc-client-id
      namespace: envoy-gateway
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-client-secret
  namespace: envoy-gateway
spec:
  encryptedData:
    client-secret: AgCit7IXaq93az7HuMVf15PhVJKRxI+dguk9Wwtr5eBEC2gBWEpARECbtYFjqrdAzqIYPnGyhoa0ETHD1wntRHPTA+HYdh+E0VJ8RNnkKiUCwCoV0kfEmgf//LtTED6NyfdhCd+Ihr4Jzdhk5TSMS8e7TV9FXkEiuZO1dDXQHaT7X/86kCcTAlT5CxOw1Ous9xatX6fJQhBKi3eepAwA3K0mtuieprINUM3p5fUkc52iMmIcSUjEnsc2j8E53IEj260ib4A7dyNWu/UI36IvwhLxULSfqHAzQeTFDk1MF1KSiK7fEd9MutlFDlCGD5de3hUHOkJDhz3wte0f1RQVM55Rt/KFXvA3lSO4PxFp5gnfNi97wMsXFL6VTcXY4eENc68tz9Y+FyyvGQU8Bs8mR/ivDm8fKs7GV5J3JJ0tZshSVZR5LFqPcabTQ7zdIBxsIusvFjlhp3B0hCg+I8Jnc3+shSZBOjKH/wJ+7OrYxq+xeoM0w0SryPElCQMH9r3N1CPL4KaCIUAMAZF2M/9bic64FNwcSlr9vaYW8qZpvPPVP3kxivOyoE2eCspxkN+mmeIhIkit9mmDOVzksfvRqMtLBYFBnDnZOrgpP3M3XU/dZZY6opV/PvjHJAJ7qENyB3T/xbUM3oHcbc8c/1y3vSH424TP1waSwrMFjfc4v+D3ZNcRyzp9DKs8z04INIovBXGu7iUCkCg7J6iEli3KxrvV60oyQ+sI83TQ81WDZmxCfaulPQ==
  template:
    metadata:
      name: oidc-client-secret
      namespace: envoy-gateway
    type: Opaque
