apiVersion: gateway.envoyproxy.io/v1alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-policy
spec:
  serviceSelector:
    matchLabels: {}  # Matches all LoadBalancer services
  externalIPs: true
  loadBalancerIPs: true
