apiVersion: v2
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-policy
spec:
  serviceSelector:
    matchLabels: {}  # Matches all LoadBalancer services
  externalIPs: true
  loadBalancerIPs: true
