revisionHistoryLimit: 3

storageClass: platform-rwo

gateway:
  name: envoy-gateway
  namespace: envoy-gateway
  sectionName: web-https

hostname: nextcloud.joeriberman.nl

nextcloud:
  image: nextcloud:34-apache@sha256:368cd1c75bc4a32c2aee8a119cae31bcebff80c374782f404c440c3295726814
  configStorage: 5Gi
  dataStorage: 100Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  cron:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi

postgres:
  image: postgres:16@sha256:e17e86066e5ef83e0952a9347f5c792b7ece00972e2aa787a6986f471b3dd3d5
  storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi

redis:
  image: redis:7-alpine@sha256:e7723ff73d963f5cc6d9c4643ea3d989527a402a319239054e9472a7fb9219a2
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      memory: 128Mi
