{{- if .Values.route.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca-bundle
  namespace: {{ .Release.Namespace }}
data:
  ca.crt: |
{{ .Values.caCertificate | indent 4 }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: vault-ui
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: ''
      kind: Service
      name: {{ .Values.route.backend.serviceName }}
  validation:
    caCertificateRefs:
      - group: ''
        kind: ConfigMap
        name: vault-ca-bundle
    hostname: vault.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
