{{- if .Values.route.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault
spec:
  parentRefs:
    - name: {{ .Values.route.parentGateway.name | quote }}
      namespace: {{ .Values.route.parentGateway.namespace | quote }}
      {{- if .Values.route.parentGateway.sectionName }}
      sectionName: {{ .Values.route.parentGateway.sectionName | quote }}
      {{- end }}
  hostnames:
    - {{ .Values.route.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.route.backend.serviceName | quote }}
          port: {{ .Values.route.backend.port }}
{{- end }}