{{- if .Values.route.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  {{- $labels := .Values.route.labels | default dict -}}
  {{- if .Values.route.oidc.enabled }}
    {{- $_ := set $labels (.Values.route.oidc.labelKey | default "auth.joeriberman.nl/oidc") (.Values.route.oidc.labelValue | default "true") -}}
  {{- end }}
  {{- if $labels }}
  labels:
  {{- range $k, $v := $labels }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
spec:
  parentRefs:
    - group: {{ .Values.route.parentGateway.group | quote }}
      kind: {{ .Values.route.parentGateway.kind | quote }}
      name: {{ .Values.route.parentGateway.name | quote }}
      namespace: {{ .Values.route.parentGateway.namespace | quote }}
      {{- if .Values.route.parentGateway.sectionName }}
      sectionName: {{ .Values.route.parentGateway.sectionName | quote }}
      {{- end }}
  hostnames:
    - {{ .Values.route.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: {{ .Values.route.backend.group | quote }}
          kind: {{ .Values.route.backend.kind | quote }}
          name: {{ .Values.route.backend.serviceName | quote }}
          port: {{ .Values.route.backend.port }}
          weight: {{ .Values.route.backend.weight }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-policy-vault
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: vault
  oidc:
    provider:
      issuer: https://accounts.google.com
    redirectURL: "https://vault.joeriberman.nl/oauth2/callback"
    clientIDRef:
      name: oidc-client-id
    clientSecret:
      name: oidc-client-secret
    cookieNames:
      idToken: id-token
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        name: allow-specific-email
        principal:
          jwt:
            provider: google
            claims:
              - name: email
                values:
                  - joeriberman@gmail.com
  jwt:
    providers:
      - name: google
        issuer: https://accounts.google.com
        remoteJWKS:
          uri: https://www.googleapis.com/oauth2/v3/certs
        extractFrom:
          cookies:
          - id-token
{{- end }}