apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: Vault Internal CA
  secretName: vault-ca-tls
  duration: 43800h  # 5y
  renewBefore: 8760h  # 1y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: vault-selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: vault-ca-tls
