apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: umami
    {{- include "services.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: umami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: umami
        app.kubernetes.io/part-of: services
    spec:
      containers:
        - name: umami
          image: {{ .Values.umami.image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: UMAMI_DATABASE_URL
            - name: DATABASE_TYPE
              value: postgresql
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: UMAMI_APP_SECRET
            - name: TRACKER_SCRIPT_NAME
              value: script.js
            - name: DISABLE_TELEMETRY
              value: "true"
          ports:
            - name: http
              containerPort: 3000
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
          resources:
            {{- toYaml .Values.umami.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: umami
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: umami
  ports:
    - name: http
      port: 3000
      targetPort: http
