apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-google-source
  namespace: {{ .Release.Namespace }}
data:
  google-source.yaml: |
    version: 1
    metadata:
      name: Google source
    entries:
      - model: authentik_sources_oauth.oauthsource
        identifiers:
          slug: google
        attrs:
          name: Google
          slug: google
          enabled: true
          promoted: true
          provider_type: google
          consumer_key: !Env AUTHENTIK_GOOGLE_CLIENT_ID
          consumer_secret: !Env AUTHENTIK_GOOGLE_CLIENT_SECRET
          authentication_flow: !Find [authentik_flows.flow, [slug, default-source-authentication]]
          enrollment_flow: !Find [authentik_flows.flow, [slug, default-source-enrollment]]
          user_matching_mode: email_link
      - model: authentik_stages_identification.identificationstage
        identifiers:
          name: default-authentication-identification
        attrs:
          sources:
            - !Find [authentik_sources_oauth.oauthsource, [slug, google]]
          show_source_labels: true
