{{- range $claim := list "data-authentik-postgresql-0" "authentik-postgresql-pg18" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claim }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false,ServerSideApply=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ $.Values.authentik.postgresql.primary.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ $.Values.authentik.postgresql.primary.persistence.size }}
---
{{- end }}
