image: binwiederhier/ntfy@sha256:081b53dbb20674fcfe05fdb4eb8af9036a2645ef979543d16f7f80803af467b1
hostname: ntfy.joeriberman.nl
storageClassName: observability-rwo
storageSize: 1Gi

route:
  parentGateway:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    namespace: envoy-gateway
    sectionName: web-https
