image: binwiederhier/ntfy:v2.29.0@sha256:4c599cf0818965782f93f652bd843e92714992e84d6b88ad17713dc0951cda1f
hostname: ntfy.joeriberman.nl
storageClassName: observability-rwo
storageSize: 1Gi

route:
  parentGateway:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    namespace: envoy-gateway
    sectionName: web-https
