image: binwiederhier/ntfy:v2.28.0@sha256:6ef4b819f722fccdc036af611c4774cfdc2de821ab74fdd48bbf4c9d6f8973da
hostname: ntfy.joeriberman.nl
storageClassName: observability-rwo
storageSize: 1Gi

route:
  parentGateway:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    namespace: envoy-gateway
    sectionName: web-https
