{{- range $name, $route := .Values.adminRoutes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik-outpost-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $.Values.route.parentGateway.name }}
      namespace: {{ $.Values.route.parentGateway.namespace }}
      sectionName: {{ $.Values.route.parentGateway.sectionName }}
  hostnames:
    - {{ $route.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /outpost.goauthentik.io
      backendRefs:
        - group: ""
          kind: Service
          name: authentik-server
          namespace: authentik
          port: 80
---
{{- end }}
