apiVersion: v2
name: argocd
version: 1.0.0
annotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

dependencies:
  - name: argo-cd
    version: 9.2.3
    repository: https://argoproj.github.io/argo-helm
