---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCPSgwPXU0BxkdsKKbVQvlQocEyEreQb5Y1qxplpofw8Rr7ZWmekcJrf2EJwkCv80JfwWUg+gcihbL7mB3eOokqPwJiXdY7yes1X7QVwtrnRvUKjbnF27nZyQSAUUb/xVeGPyU3y5iq9PSYDzM6cYBaw4eKCDXKPZhVn+qutdg2PlrEJp2O0iYcbYEtid9JAEx4kvUNUIka0R5oGqJUODN+INdNg/kJeXgH2GpZk7MhAhIwGNexjJkV2nFuRHZCW9ITpEIykrCTiWfITW7BA2zeDm3oCgWh6kTtk9PZ2IYVEusiXyhTW7fHCRMf9VxKFqNSG/p9VfUEYhrf7SkPQVZPITyI7MCq+g6IgZ0KxaycwSBzownVwwEIrRxHXU2Fv5gtBGw9ZB/Ix5P634R38LmDaMIJB9h7u2vrQ0Eq1mmY9qBFiuA3KdCsEQ6uD9+pRykISacduMJMNdF8mlhAhPIbLPuP5dOtCM3Ck9DhInMAO3675+Sf5lcXj6+XhABLfLPoE/i7wiCv1/aYJJKZIJfnRSGjGxNyKwAq+8vVrJAlIWqciOjGVpJqMBIsxJ02gyKRaqMGmAGBbouHJA1CRwidiEqOQC9MnlkfMuWQWoq24jd4EMdF9D7LcKVTL09K8/SoZRXUCGhyhK6uZERDPXB4KVXoZnLbtekTcl98QCVqVFYUJEGt8pg2KELQhwvWLkWRQFcsVN+uVlln2ql0IfABOD5pCYBNDBSFQ/Nh043ZmqHCjo1tpBfk
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
