---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCGfJJSsNaYMFZarBMCqxpz7yYAGvefkn/qUAUG//IlsxOnYeOA6eeaFvF7+JfoLHDLnYE0H9jGIQcEXhUstwXekrFUmmuuLuETwLgAWYOQ6B+N62DUkVxTAlhh2sqeisScGkrxuEeAmnB3K0nuWMuVvzlfmtfZ8Wobx0vRV1ellAdWoDutmt6ud5TzLmuCbhneiI1kfXByJMweWXn8S28D/TWx6Bms52bA/DhocAsIgDrJe6fLy/fSXhhO6Y4v30aHZWGpfFBi5ysWP3KojNoJCyOfxRLOK4dnoj0siY/p/jaSryN7dHHaqdSKa8rPz89Avja/kbucdEU+FhPgmZ8GVYelQglsp2Z15D+83DA8rqV3qhtfeXXHq7hiKbtrugm1fAs0vRg0fOYDDld+28NtyVvDFx9q3G5d9FlnZPQyN0eaEifbt3rJ3E9GV3InM3T5e1HDMG4R+8x/1aeF35z85OnmYzrxgYy59a/lfOSpUpU1HueNHEcAXRXxiC3D8PL1DC1vMltimJwLuPyTFJ2yodVdAAp/mV+GKqbenTQrqAp2DgmjS6wf+uVHJVRZPL8F5vXdrHJZzvgtlrisUYC05IGOBRyZ9H84zfwHrMg0WOGbL4TFsQ9238rDLcd1OR8pRFr0P+oVs28j0NS5GtiliYJXiWj7sTyp0If7f4UQN+tKuGi2JJcj73NpKysrchGyFYDYJaJY+B1YrZ+KbMR3aX1sCAWchZS1coAAqItDALIcJGXzfOn+
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
