---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBxDUbakibha2hkv0QsJUofHFizd+aAmRV+4pH6jnDYZAE/hVQj6gQJ5PtBAnTMzrxf3Js56L20tX5t/ED4q/yHag0PSGg/ncPmqzo7Q7WwDCrUytLuIZLWTeqVJwTeeluM9dp2IiP1YrdVeV8lrajgSRyoi6A1uj7E7qbb8Ne3oFFtB0aXWQdHKl4Ax1BgR73ryTs0RwV3OKkZHo8aSxwDytbkMAw4rpY++bojpQGGkbr+rY/Xekom7D2/bunnPKGnrUb/nf9SLAcBC4NTGJ7lU8AAMy118iwblJInfEdfixflDF/zTYPuLi/kIYJGrgTbSuBwI80ApwNJsR6UTgqRMsDEA5+K3WR0YI4SQvT/Wr9S1wZbesy+CbT/xjo7TSzQGA87beSbTje28ZHwqy72RD1KXrZ38sRPyW3c9/rgE/W9qWNWwi8KRl5Ktha617APN4t5rywlfIsttC+yV10mtIgV490ANulwdwTdsbtJXLW6G+nf4TMj1uYYx37r++FtsPzeMv0rRmJCgi81WFvKx2vTW0hIN28iVF5+CPjNPPRizBz1ZA8ZMfzFlIBWcjKuvn+qSQhJcFrYaobjXHwf8mmnITiBn/kqXqAK6AzUc9aJ40MjU0/Vdj+ebLBTo5+ILI18PdxlGNDRFG5HvZRvdzEQzDNuk38KYNzoDjVnR1UV7OYKHQcG2mH0lF9ePXLjPwOUkm6LeHxjwAQt4ALFlYm9RjAx3Lo3Z9EaLPwkjD+DNqZi7BgrFQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
