apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Chazler/homelab-cluster.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
      include: '*.yaml'
      exclude: '{**/Chart.yaml,**/values.yaml,**/templates/**,**/charts/**,.helmignore}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
