apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Chazler/homelab-cluster.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
      exclude: '{**/values.yaml,**/Chart.yaml,**/Chart.lock,**/README.md,**/*.txt,**/templates/**/*,**/charts/**/*}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
