{{- if .Values.policies.envoyOidc.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-envoy-oidc-securitypolicy
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: clone-oidc-client-id
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - gateway.networking.k8s.io/v1/HTTPRoute
              selector:
                matchLabels:
                  {{ .Values.policies.envoyOidc.labelKey }}: {{ .Values.policies.envoyOidc.labelValue | quote }}
      generate:
        apiVersion: v1
        kind: Secret
        name: {{ required "policies.envoyOidc.clientIDSecretName is required when enabled" .Values.policies.envoyOidc.clientIDSecretName | quote }}
        namespace: {{ "{{request.object.metadata.namespace}}" | quote }}
        synchronize: true
        clone:
          namespace: {{ required "policies.envoyOidc.secretNamespace is required when enabled" .Values.policies.envoyOidc.secretNamespace | quote }}
          name: {{ required "policies.envoyOidc.clientIDSecretName is required when enabled" .Values.policies.envoyOidc.clientIDSecretName | quote }}

    - name: clone-oidc-client-secret
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - gateway.networking.k8s.io/v1/HTTPRoute
              selector:
                matchLabels:
                  {{ .Values.policies.envoyOidc.labelKey }}: {{ .Values.policies.envoyOidc.labelValue | quote }}
      generate:
        apiVersion: v1
        kind: Secret
        name: {{ required "policies.envoyOidc.clientSecretName is required when enabled" .Values.policies.envoyOidc.clientSecretName | quote }}
        namespace: {{ "{{request.object.metadata.namespace}}" | quote }}
        synchronize: true
        clone:
          namespace: {{ required "policies.envoyOidc.secretNamespace is required when enabled" .Values.policies.envoyOidc.secretNamespace | quote }}
          name: {{ required "policies.envoyOidc.clientSecretName is required when enabled" .Values.policies.envoyOidc.clientSecretName | quote }}

    - name: generate-securitypolicy-protected
      match:
        any:
          - resources:
              kinds:
                - gateway.networking.k8s.io/v1/HTTPRoute
              selector:
                matchLabels:
                  {{ .Values.policies.envoyOidc.labelKey }}: {{ .Values.policies.envoyOidc.labelValue | quote }}
      {{- if .Values.policies.envoyOidc.emailWhitelist }}
      exclude:
        any:
          - resources:
              names:
                - auth
      {{- end }}
      skipBackgroundRequests: true
      generate:
        apiVersion: gateway.envoyproxy.io/v1alpha1
        kind: SecurityPolicy
        name: oidc-{{ "{{request.object.metadata.name}}" }}
        namespace: {{ "{{request.object.metadata.namespace}}" | quote }}
        synchronize: true
        data:
          apiVersion: gateway.envoyproxy.io/v1alpha1
          kind: SecurityPolicy
          metadata:
            name: oidc-{{ "{{request.object.metadata.name}}" }}
            namespace: {{ "{{request.object.metadata.namespace}}" | quote }}
          spec:
            targetRef:
              group: gateway.networking.k8s.io
              kind: HTTPRoute
              name: {{ "{{request.object.metadata.name}}" | quote }}
            oidc:
              provider:
                issuer: {{ required "policies.envoyOidc.issuer is required when enabled" .Values.policies.envoyOidc.issuer | quote }}
              redirectURL: "https://{{ "{{request.object.spec.hostnames[0]}}" }}/oauth2/callback"
              {{- if .Values.policies.envoyOidc.cookieDomain }}
              cookieDomain: {{ .Values.policies.envoyOidc.cookieDomain | quote }}
              {{- end }}
              cookieNames:
                idToken: id-token
              clientIDRef:
                name: {{ default (required "policies.envoyOidc.clientSecretName is required when enabled" .Values.policies.envoyOidc.clientSecretName) .Values.policies.envoyOidc.clientIDSecretName | quote }}
              clientSecret:
                name: {{ required "policies.envoyOidc.clientSecretName is required when enabled" .Values.policies.envoyOidc.clientSecretName | quote }}
            {{- if .Values.policies.envoyOidc.emailWhitelist }}
            authorization:
              defaultAction: Deny
              rules:
                - action: Allow
                  name: allow-whitelisted-emails
                  principal:
                    jwt:
                      provider: google
                      claims:
                        - name: email
                          values:
                            {{- range .Values.policies.envoyOidc.emailWhitelist }}
                            - {{ . | quote }}
                            {{- end }}
            {{- end }}

    {{- if .Values.policies.envoyOidc.emailWhitelist }}
    - name: generate-securitypolicy-auth
      match:
        all:
          - resources:
              kinds:
                - gateway.networking.k8s.io/v1/HTTPRoute
              names:
                - auth
              selector:
                matchLabels:
                  {{ .Values.policies.envoyOidc.labelKey }}: {{ .Values.policies.envoyOidc.labelValue | quote }}
      skipBackgroundRequests: true
      generate:
        apiVersion: gateway.envoyproxy.io/v1alpha1
        kind: SecurityPolicy
        name: oidc-{{ "{{request.object.metadata.name}}" }}
        namespace: {{ "{{request.object.metadata.namespace}}" | quote }}
        synchronize: true
        data:
          apiVersion: gateway.envoyproxy.io/v1alpha1
          kind: SecurityPolicy
          metadata:
            name: oidc-{{ "{{request.object.metadata.name}}" }}
            namespace: {{ "{{request.object.metadata.namespace}}" | quote }}
          spec:
            targetRef:
              group: gateway.networking.k8s.io
              kind: HTTPRoute
              name: {{ "{{request.object.metadata.name}}" | quote }}
            oidc:
              provider:
                issuer: {{ required "policies.envoyOidc.issuer is required when enabled" .Values.policies.envoyOidc.issuer | quote }}
              redirectURL: "https://{{ "{{request.object.spec.hostnames[0]}}" }}/oauth2/callback"
              {{- if .Values.policies.envoyOidc.cookieDomain }}
              {{- end }}
              clientIDRef:
                name: {{ default (required "policies.envoyOidc.clientSecretName is required when enabled" .Values.policies.envoyOidc.clientSecretName) .Values.policies.envoyOidc.clientIDSecretName | quote }}
              clientSecret:
                name: {{ required "policies.envoyOidc.clientSecretName is required when enabled" .Values.policies.envoyOidc.clientSecretName | quote }}
    {{- end }}
{{- end }}
