{{- if .Values.policies.envoyOidc.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-envoy-oidc-secrets
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: clone-oidc-client-id
      skipBackgroundRequests: false
      match:
        any:
          - resources:
              kinds:
                - v1/Namespace
              selector:
                matchLabels:
                  {{ .Values.policies.envoyOidc.namespaceLabelKey }}: {{ .Values.policies.envoyOidc.namespaceLabelValue | quote }}
      generate:
        apiVersion: v1
        kind: Secret
        name: {{ required "policies.envoyOidc.clientIDSecretName is required when enabled" .Values.policies.envoyOidc.clientIDSecretName | quote }}
        namespace: {{ "{{request.object.metadata.name}}" | quote }}
        synchronize: true
        clone:
          namespace: {{ required "policies.envoyOidc.secretNamespace is required when enabled" .Values.policies.envoyOidc.secretNamespace | quote }}
          name: {{ required "policies.envoyOidc.clientIDSecretName is required when enabled" .Values.policies.envoyOidc.clientIDSecretName | quote }}

    - name: clone-oidc-client-secret
      skipBackgroundRequests: false
      match:
        any:
          - resources:
              kinds:
                - v1/Namespace
              selector:
                matchLabels:
                  {{ .Values.policies.envoyOidc.namespaceLabelKey }}: {{ .Values.policies.envoyOidc.namespaceLabelValue | quote }}
      generate:
        apiVersion: v1
        kind: Secret
        name: {{ required "policies.envoyOidc.clientSecretName is required when enabled" .Values.policies.envoyOidc.clientSecretName | quote }}
        namespace: {{ "{{request.object.metadata.name}}" | quote }}
        synchronize: true
        clone:
          namespace: {{ required "policies.envoyOidc.secretNamespace is required when enabled" .Values.policies.envoyOidc.secretNamespace | quote }}
          name: {{ required "policies.envoyOidc.clientSecretName is required when enabled" .Values.policies.envoyOidc.clientSecretName | quote }}
{{- end }}
