apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Chazler/homelab-cluster.git
    targetRevision: main
    path: apps/core/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - DisableClientSideApplyMigration=true
      - ServerSideApplySkipResources=apiextensions.k8s.io/CustomResourceDefinition