apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authentik-outpost
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames: [authentik]
  selector:
    matchLabels:
      goauthentik.io/service-type: metrics
      goauthentik.io/outpost-name: homelab-forward-auth
  endpoints:
    - port: http-metrics
      interval: 60s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames: [envoy-gateway]
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-helm
      control-plane: envoy-gateway
  endpoints:
    - port: metrics
      interval: 60s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames: [longhorn]
  selector:
    matchLabels:
      app: longhorn-manager
  endpoints:
    - port: manager
      interval: 60s
