apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    authentik-forward-auth: "true"
spec:
  parentRefs:
    - group: {{ .Values.route.parentGateway.group | quote }}
      kind: {{ .Values.route.parentGateway.kind | quote }}
      name: {{ .Values.route.parentGateway.name | quote }}
      namespace: {{ .Values.route.parentGateway.namespace | quote }}
      sectionName: {{ .Values.route.parentGateway.sectionName | quote }}
  hostnames:
    - grafana.joeriberman.nl
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: observability-grafana
          port: 80
          weight: 1
